ALTER TABLE command_usage
    ALTER COLUMN used_at TYPE TIMESTAMP WITH TIME ZONE USING used_at::TIMESTAMP WITH TIME ZONE;

ALTER TABLE giveaways
    ALTER COLUMN expires_in TYPE TIMESTAMP WITH TIME ZONE USING expires_in::TIMESTAMP WITH TIME ZONE;

ALTER TABLE join_dates
    ALTER COLUMN first_join TYPE TIMESTAMP WITH TIME ZONE USING first_join::TIMESTAMP WITH TIME ZONE;

ALTER TABLE last_seen_users
    ALTER COLUMN last_seen TYPE TIMESTAMP WITH TIME ZONE USING last_seen::TIMESTAMP WITH TIME ZONE;

ALTER TABLE polls
    ALTER COLUMN expires_in TYPE TIMESTAMP WITH TIME ZONE USING expires_in::TIMESTAMP WITH TIME ZONE;
ALTER TABLE polls
    ALTER COLUMN expires_in TYPE TIMESTAMP WITH TIME ZONE USING expires_in::TIMESTAMP WITH TIME ZONE;

ALTER TABLE role_cooldown
    ALTER COLUMN last_use TYPE TIMESTAMP WITH TIME ZONE USING last_use::TIMESTAMP WITH TIME ZONE;

ALTER TABLE temproles
    ALTER COLUMN expires_at TYPE TIMESTAMP WITH TIME ZONE USING expires_at::TIMESTAMP WITH TIME ZONE;

ALTER TABLE timeout_logs
    ALTER COLUMN "time" TYPE TIMESTAMP WITH TIME ZONE USING "time"::TIMESTAMP WITH TIME ZONE;

ALTER TABLE timeouts
    ALTER COLUMN expires_on TYPE TIMESTAMP WITH TIME ZONE USING expires_on::TIMESTAMP WITH TIME ZONE;

ALTER TABLE todo
    ALTER COLUMN "time" TYPE TIMESTAMP WITH TIME ZONE USING "time"::TIMESTAMP WITH TIME ZONE;
ALTER TABLE todo
    ALTER COLUMN completed_at TYPE TIMESTAMP WITH TIME ZONE USING completed_at::TIMESTAMP WITH TIME ZONE;
